name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ dev, master ]

jobs:
  environment-variables:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    runs-on: [ runnerDeployment ]
    steps:
      - name: Setup environment variables
        id: environment-variables
        run: |
          ## Configure env variables ##
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
                      
              ENVIRONMENT="dev" 

          elif [[ "${{ github.ref_name }}" == "master" ]]; then
                      
              ENVIRONMENT="prod" 

          else
            echo -e "Wrong branch to build"
            exit 1
          fi
                  
          echo -e "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT 


    outputs:
          
      environment: ${{ steps.environment-variables.outputs.ENVIRONMENT }} 


  build-and-push:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    needs: [ environment-variables ]
    uses: NetkiCorp/devops-pipelines/.github/workflows/build.yml@master
    with:
      APP_NAME:       keychain
      BUILD_TAG:      ${{ needs.environment-variables.outputs.environment }}_${{ github.run_id }}
      ENVIRONMENT:    ${{ needs.environment-variables.outputs.environment }}
      BUILD_ARGS:     ""
      BUILD_CONTEXT:  
      DOCKERFILE:     Dockerfile
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    needs: [ environment-variables, build-and-push ]
    uses: NetkiCorp/devops-pipelines/.github/workflows/deploy.yml@master
    secrets: inherit
    with:
      APP_NAME:       keychain
      BUILD_TAG:      ${{ needs.environment-variables.outputs.environment }}_${{ github.run_id }}
      ENVIRONMENT:    ${{ needs.environment-variables.outputs.environment }}
            

